# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "History" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"detail" VARCHAR NOT NULL,"historyDate" TIMESTAMP NOT NULL,"dataType" VARCHAR NOT NULL,"dataGroup" INTEGER NOT NULL,"account" VARCHAR NOT NULL,"amount" DECIMAL(21,2) NOT NULL);
create table "IrregularItem" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"occurDate" TIMESTAMP NOT NULL,"name" VARCHAR NOT NULL,"itemType" VARCHAR NOT NULL,"amount" DECIMAL(21,2) NOT NULL);
create table "RegularItem" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"itemType" VARCHAR NOT NULL,"amount" DECIMAL(21,2) NOT NULL);

# --- !Downs

drop table "RegularItem";
drop table "IrregularItem";
drop table "History";

